import type { RichPreviewKind } from './richAttachmentPreview';

export function richPreviewHtml(runtime: string, payload: { kind: RichPreviewKind; base64: string }): string {
    // File bytes are base64 data, never interpolated markup or executable code.
    const nonce = `muxr-${Math.random().toString(36).slice(2)}-${Date.now().toString(36)}`;
    const script = `${runtime}\nvoid window.renderMuxrAttachment(${JSON.stringify(payload)});`.replace(/<\/script/gi, '<\\/script');
    return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-${nonce}' blob:; worker-src blob:; style-src 'unsafe-inline'; img-src data: blob:; font-src data:; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'"><style>
:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#fff;color:#202329;font:16px/1.65 system-ui,sans-serif}#tools{position:sticky;top:0;display:flex;gap:8px;flex-wrap:wrap;padding:8px;background:#f4f5f7;border-bottom:1px solid #ddd;z-index:1}#tools:empty{display:none}button,select{min-height:44px;border:1px solid #ccd0d5;border-radius:8px;background:white;color:#202329;padding:6px 12px;font:inherit}#content{padding:20px;overflow:auto}#status{font:12px/1.5 system-ui;color:#59616e;padding:12px 20px;border-top:1px solid #eee}pre,code{font-family:ui-monospace,monospace}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f4f5f7;padding:12px;border-radius:8px}table{border-collapse:collapse;font-size:14px}td,th{border:1px solid #ddd;padding:8px 12px;max-width:360px;overflow-wrap:anywhere;text-align:left}th{background:#f4f5f7}img,svg{max-width:100%;height:auto}canvas{display:block;margin:auto}h1,h2,h3{line-height:1.25}blockquote{margin-left:0;padding-left:16px;border-left:3px solid #ccc}</style></head><body><div id="tools"></div><main id="content"></main><div id="status" role="status">Opening preview…</div><script nonce="${nonce}">${script}</script></body></html>`;
}
