/** Public API of the host's desktop feature. Import this, not internals. */
export { DesktopSessions, type DesktopEngineOptions } from './infrastructure/desktopSessions.js';
export { nextDesktopId, type DesktopSessionRecord } from './domain/desktopSession.js';
export { PaneScreens, type PaneScreen, type ScreenWindow } from './infrastructure/paneScreens.js';
export {
    PreviewDesktops,
    PreviewPresenceTracker,
    cleanPreviewTitle,
    previewKindForClass,
    withPreview,
    type PreviewDesktopsOptions,
    type PreviewPresenceTrackerOptions,
    type PreviewScreenWindow,
    type PreviewScreens,
} from './application/previewPresence.js';
export {
    AndroidEmulatorWatcher,
    AndroidMirrors,
    AndroidPreviewTargets,
    AndroidPresenceTracker,
    DesklinkEncodedEngine,
    androidCapabilities,
    avdTitle,
    deviceOnline,
    findAdb,
    resolveScrcpyServer,
    scanAndroidEmulators,
    withAndroidPreview,
    type AdbRunner,
    type AdbResult,
    type AndroidMirrorOptions,
    type AndroidTargetsOptions,
    type AndroidWatcherOptions,
    type DiscoveredEmulator,
    type EncodedEngine,
    type EncodedEngineEvent,
    type EncodedEngineOptions,
    type EncodedEngineSession,
    type EncodedInput,
} from './application/androidEmulators.js';
export {
    ANDROID_ACTION_DOWN,
    ANDROID_ACTION_UP,
    ANDROID_KEYCODE_APP_SWITCH,
    ANDROID_KEYCODE_HOME,
    RESET_VIDEO_MESSAGE,
    ROTATE_DEVICE_MESSAGE,
    ScrcpyVideoParser,
    encodeBackOrScreenOn,
    encodeInjectKeycode,
    encodeScroll,
    encodeText,
    encodeTouch,
    toAccessUnit,
} from './application/scrcpy.js';
