apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.voiceoverlay'
version = '0.1.0'

android {
  namespace 'expo.modules.voiceoverlay'
  compileSdk rootProject.ext.has('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 36
  defaultConfig {
    minSdk rootProject.ext.has('minSdkVersion') ? rootProject.ext.minSdkVersion : 24
  }
  kotlinOptions { jvmTarget = '17' }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation 'androidx.core:core-ktx:1.17.0'
  implementation "org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}"
}
