/**
 * The WebView terminal page, shared by the full terminal and the home-screen
 * preview cards. Native only -- web runs xterm directly in the DOM.
 *
 * xterm is vendored into the app bundle (terminalAssets.ts, generated by
 * scripts/genTerminalAssets.mjs from node_modules): no CDN, works offline and
 * on LAN-only relays, and matches the web's xterm version exactly.
 */
import { FIT_ADDON_JS, WEBGL_ADDON_JS, XTERM_CSS, XTERM_JS } from './terminalAssets';

export function terminalHtml(options: { fontSize: number; interactive: boolean }): string {
    return `<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<style>
${XTERM_CSS}
html,body,#t{margin:0;padding:0;height:100%;background:#0c0c0b;overflow:hidden}
/* Without this the browser claims a vertical drag for native scrolling and the
   touch handler below never sees touchmove on a real device. */
#t,.xterm,.xterm-viewport,.xterm-screen{touch-action:none;overscroll-behavior:none}
</style>
</head>
<body>
<div id="t"></div>
<script>${XTERM_JS}</script>
<script>${FIT_ADDON_JS}</script>
<script>${WEBGL_ADDON_JS}</script>
<script>
(function () {
  var post = function (message) { window.ReactNativeWebView.postMessage(JSON.stringify(message)); };
  if (typeof Terminal === 'undefined') { post({ type: 'error', message: 'xterm failed to load' }); return; }
  var term = new Terminal({
    fontSize: ${options.fontSize},
    theme: { background: '#0c0c0b' },
    scrollback: 5000,
    cursorBlink: ${options.interactive},
    disableStdin: ${!options.interactive},
  });
  var fit = new FitAddon.FitAddon();
  term.loadAddon(fit);
  term.open(document.getElementById('t'));
  fit.fit();
  // WebGL renderer where the WebView allows it; canvas fallback otherwise.
  try { if (typeof WebglAddon !== 'undefined') term.loadAddon(new WebglAddon.WebglAddon()); } catch (e) {}
  term.onData(function (data) { post({ type: 'input', data: data }); });
  window.addEventListener('resize', function () { fit.fit(); post({ type: 'size', cols: term.cols, rows: term.rows }); });
  // herdr owns the pane's scrollback and repaints the viewport, so xterm's own
  // buffer holds frames rather than history -- scrolling it here shows garbage.
  // Forward the drag to herdr instead: it scrolls the REAL pane, so the
  // terminal scrolls in place. Touch is content-follows-finger, like every
  // native scroll surface: drag DOWN and the content moves down, revealing
  // older output above.
  // A full-screen TUI on the alternate screen has no scrollback, so herdr
  // ignores the scroll and the pane does not move -- that is the honest
  // behaviour; do not bolt a popup onto it.
  if (${options.interactive}) {
    var cellHeight = function () {
      try {
        var h = term._core._renderService.dimensions.css.cell.height;
        if (h > 0) return h;
      } catch (e) { /* private API moved -- fall back */ }
      return ${options.fontSize} * 1.4;
    };
    var scrollEl = document.getElementById('t');
    var lastY = null, accPx = 0, gesturePx = 0, velocity = 0, lastT = 0, momentumOn = false, scrollScheduled = false;
    // Same coalescing as the web build: one scroll per animation frame, with
    // decaying-velocity glide after release. Every scroll is a full RTT +
    // repaint; per-touchmove sends rubber-band.
    var emitScroll = function () {
      scrollScheduled = false;
      var lines = Math.trunc(accPx / cellHeight());
      if (lines === 0) return;
      var clamped = Math.max(-40, Math.min(40, lines));
      post({ type: 'scroll', lines: clamped });
      accPx -= clamped * cellHeight();
      if (lines !== clamped) accPx = 0;
    };
    var scheduleScroll = function () {
      if (scrollScheduled) return;
      scrollScheduled = true;
      requestAnimationFrame(emitScroll);
    };
    var momentum = function () {
      if (Math.abs(velocity) < 0.5) { momentumOn = false; return; }
      accPx += velocity;
      velocity *= 0.94;
      emitScroll();
      requestAnimationFrame(momentum);
    };
    scrollEl.addEventListener('touchstart', function (e) {
      velocity = 0; momentumOn = false;
      if (e.touches.length !== 1) { lastY = null; return; }
      lastY = e.touches[0].clientY; lastT = performance.now(); accPx = 0; gesturePx = 0;
    }, { capture: true, passive: true });
    scrollEl.addEventListener('touchmove', function (e) {
      if (lastY === null || e.touches.length !== 1) return;
      var y = e.touches[0].clientY;
      var now = performance.now();
      var dy = y - lastY; // finger down = content down = older output
      var dt = now - lastT;
      if (dt > 0 && dt < 100) velocity = velocity * 0.7 + (dy / dt) * 16.7 * 0.3;
      accPx += dy;
      gesturePx += dy;
      lastY = y; lastT = now;
      if (Math.abs(gesturePx) < 8) return; // slop: taps stay taps
      e.preventDefault();
      e.stopPropagation();
      scheduleScroll();
    }, { capture: true, passive: false });
    scrollEl.addEventListener('touchend', function () {
      lastY = null; gesturePx = 0;
      if (!momentumOn && Math.abs(velocity) >= 0.5) { momentumOn = true; requestAnimationFrame(momentum); }
    }, { capture: true, passive: true });
  }
  // Frames arrive base64 from RN; write bytes so xterm handles the ANSI itself.
  // Batched: one write per animation frame during repaint bursts.
  var pendingBytes = [], frameScheduled = false;
  var flushFrames = function () {
    frameScheduled = false;
    if (pendingBytes.length === 0) return;
    var chunks = pendingBytes; pendingBytes = [];
    var total = 0, i;
    for (i = 0; i < chunks.length; i++) total += chunks[i].length;
    var all = new Uint8Array(total), off = 0;
    for (i = 0; i < chunks.length; i++) { all.set(chunks[i], off); off += chunks[i].length; }
    term.write(all);
  };
  window.__write = function (base64) {
    var binary = atob(base64);
    var bytes = new Uint8Array(binary.length);
    for (var i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    pendingBytes.push(bytes);
    if (!frameScheduled) { frameScheduled = true; requestAnimationFrame(flushFrames); }
  };
  post({ type: 'ready', cols: term.cols, rows: term.rows });
})();
true;
</script>
</body>
</html>`;
}
