/**
 * Generates sources/terminal/terminalAssets.ts: the xterm UMD bundles + css
 * inlined as string exports, so the native WebView terminal works offline
 * (no CDN at runtime). Re-run after bumping @xterm/* in the root package.json.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));

const assets = {
    XTERM_CSS: ['@xterm/xterm/css/xterm.css', 'css'],
    XTERM_JS: ['@xterm/xterm/lib/xterm.js', 'js'],
    FIT_ADDON_JS: ['@xterm/addon-fit/lib/addon-fit.js', 'js'],
    WEBGL_ADDON_JS: ['@xterm/addon-webgl/lib/addon-webgl.js', 'js'],
};

let out = '/**\n * GENERATED by scripts/genTerminalAssets.mjs -- do not edit by hand.\n * Vendored xterm for the native WebView terminal (see terminalHtml.ts).\n */\n';
for (const [name, [subpath, kind]] of Object.entries(assets)) {
    let content = readFileSync(require.resolve(subpath), 'utf8');
    if (kind === 'js') {
        // A literal "</script>" inside the bundle would close the WebView's
        // inline script tag early; the backslash keeps it a valid JS string.
        content = content.replaceAll('</script', '<\\/script');
    }
    out += `\nexport const ${name} = ${JSON.stringify(content)};\n`;
}

const target = join(here, '..', 'sources', 'terminal', 'terminalAssets.ts');
writeFileSync(target, out);
console.log(`wrote ${target} (${(out.length / 1024).toFixed(0)} KB)`);
