export type { Outcome } from './shared/index.js';
export { fail, ok, unwrapOrThrow } from './shared/index.js';

export type {
    AttentionCatalog,
    AttentionEntry,
    AttentionReason,
    AgentLifecycle,
    AgentInfo,
    LifecycleCatalog,
    LifecycleEvent,
    LifecycleReasonCode,
    LifecycleNotificationLevel,
    SessionActivity,
    SessionAttachment,
    SessionChangeFile,
    SessionContextUsage,
    SessionInfo,
    HerdrTreePane,
    HerdrTreeTab,
    HerdrTreeWorkspace,
    SessionModel,
    SessionRef,
    CloseResult,
    CloseScope,
    SessionStatus,
    SessionTokens,
    SessionWarning,
    SessionShellOutcome,
    SessionEvent,
    SessionEventBody,
    SessionEventType,
    MachineInfo,
    MessagePage,
    SessionSnapshot,
    SessionStartResult,
    SessionUnreadEntry,
    UnreadCatalog,
} from './herd/index.js';
export {
    AGENT_LIFECYCLES,
    ATTENTION_DONE_TTL_MS,
    ATTENTION_HARD_CAP_MS,
    ATTENTION_REASONS,
    SESSION_EVENT_TYPES,
    agentIsWorking,
    agentRoute,
    attentionOutranks,
    attentionRank,
    attentionReasonStillHolds,
    isSessionIdle,
    lifecycleEventAgentName,
    LIFECYCLE_NOTIFICATION_LEVELS,
    lifecycleNotificationAllowed,
    lifecycleEventRoute,
    parseAgentLifecycle,
    parseLifecycleNotificationLevel,
    parseAgentName,
    parseCloseResult,
    parseCloseScope,
    parseProviderKind,
    parsePublicAgentRoute,
    CLOSE_SCOPES,
    startWasAccepted,
} from './herd/index.js';

export type {
    ClientRequest,
    PeerClientRequest,
    PeerRequestMap,
    PeerRequestParams,
    PeerRequestResult,
    PeerRequestType,
    PromptAttachment,
    RequestMap,
    RequestParams,
    RequestResponse,
    RequestResult,
    RequestType,
    StreamingBehavior,
    VoiceProviderOption,
    WatchSettlement,
    LayoutSnapshot,
    ClientFrame,
    Envelope,
    EnvelopeHeader,
    PluginsInvalidatedFrame,
    HostFrame,
    RoutingChannel,
    PreviewFrame,
    TerminalClientFrame,
    TerminalHostFrame,
    WsTransport,
} from './control-plane/index.js';
export {
    MISSING_CWD_ERROR_PREFIX,
    normalizeRequestFailure,
    requestRequiresE2ee,
    decodePayload,
    encodePayload,
    envelopeIsHosted,
    isPluginsInvalidatedFrame,
    isRoutingChannel,
    nextRequestId,
    admitClientFrame,
    parseClientFrame,
    tryParseClientFrame,
    RELAY_CLOSE_REPLACED,
    ROUTING_CHANNELS,
    decodePreviewFrame,
    encodePreviewFrame,
    newPreviewChannel,
    previewSocketUrl,
    PREVIEW_CLOSE,
    PREVIEW_DATA,
    PREVIEW_HEADER_BYTES,
    newTerminalChannel,
    terminalSocketUrl,
    relayControlUrl,
    isWebSocketRelayUrl,
    relayChannelSocketUrl,
    issueWsTicket,
    ticketSocketUrl,
    WsTicketError,
} from './control-plane/index.js';

export type {
    DeviceKind,
    PeerAuthorityMetadata,
    PeerCapability,
    PeerDescriptorClaims,
    PeerGrantConstraintError,
    PeerMutationMetadata,
    PeerMutationRejection,
    PeerRelationship,
    PeerRelationshipState,
    SignedPeerDescriptor,
} from './peer/index.js';
export {
    DEFAULT_PEER_CAPABILITIES,
    inspectPeerGrantConstraints,
    inspectPeerMutation,
    isPeerCapabilities,
    PEER_CAPABILITIES,
    PEER_MUTATION_CLOCK_SKEW_MS,
    PEER_MUTATION_MAX_TTL_MS,
    PEER_MUTATION_TTL_MS,
    parseDeviceKind,
    deviceIsPeer,
    parsePeerAllowlist,
    peerCapabilityForRequest,
    peerMayDispatch,
    authorizePeerDispatch,
    admitPeerMutation,
} from './peer/index.js';

export type { LandWorktreeResult, WorktreeLandingDecision } from './worktree/index.js';
export { interpretWorktreeLanding, landNeedsConsent, landSucceeded } from './worktree/index.js';

export type {
    PluginContribution,
    PluginManifestV1,
    PluginText,
    PluginNativeContribution,
    PluginNativeSlot,
    PluginPrimitive,
    PluginPrimitiveSpec,
    PluginPrimitiveParamRule,
    PluginNativeContextKey,
    PluginAction,
    PluginTerminalKey,
    PluginTerminalKeyRow,
    PluginDataCard,
    PluginEventAction,
    PluginEventTrigger,
    PluginShortcut,
    PluginNavigationItem,
    PluginSettingsItem,
    PluginRow,
    PluginSettingsSection,
    PluginSource,
    PluginSummary,
    PluginToolbarButton,
    PluginRpcCapability,
    PluginStreamCapability,
    PluginRpcMode,
    PluginContextRequest,
    PluginPublicAttentionContext,
    PluginPublicContext,
    PluginPublicSessionContext,
    PluginPublicTreeSession,
    PluginPublicTreeTab,
    PluginPublicTreeWorkspace,
    PluginScreenButtonNode,
    PluginScreenChartNode,
    PluginScreenCodeNode,
    PluginScreenContribution,
    PluginScreenFieldKind,
    PluginScreenFieldNode,
    PluginScreenNode,
    PluginScreenRowAction,
    PluginScreenRowNode,
    PluginScreenTreeNode,
    PluginScreenTone,
} from './plugins/index.js';
export {
    defaultPluginText,
    resolvePluginText,
    isValidPluginId,
    parsePluginId,
    MAX_PLUGIN_LOCALE_TAG_LENGTH,
    MAX_PLUGIN_TEXT_LOCALES,
    PLUGIN_TEXT_MIN_UI_VERSION,
    MAX_RPC_ARRAY_ENTRIES,
    MAX_RPC_CONCURRENCY,
    MAX_RPC_PER_PLUGIN,
    MAX_RPC_PER_DEVICE,
    PLUGIN_CALL_DEADLINE_MS,
    PLUGIN_CALL_KILL_GRACE_MS,
    PLUGIN_CALL_CLIENT_TIMEOUT_MS,
    MAX_RPC_DISPLAY_BYTES,
    MAX_RPC_DISPLAY_DEPTH,
    MAX_RPC_INPUT_BYTES,
    MAX_RPC_RESULT_STRING_BYTES,
    MAX_RPC_STDERR_BYTES,
    MAX_RPC_STDOUT_BYTES,
    MAX_PLUGIN_CONTEXT_ATTENTION,
    MAX_PLUGIN_CONTEXT_BYTES,
    MAX_PLUGIN_CONTEXT_SESSIONS,
    MAX_PLUGIN_CONTEXT_TABS,
    MAX_PLUGIN_CONTEXT_TREE_SESSIONS,
    MAX_PLUGIN_CONTEXT_WORKSPACES,
    MAX_PLUGIN_REFRESH_INTERVAL_MS,
    MIN_PLUGIN_REFRESH_INTERVAL_MS,
    MAX_SCREEN_DEPTH,
    MAX_SCREEN_FIELD_IDS,
    MAX_SCREEN_LIST_ROWS,
    MUXR_UI_VERSION,
    DYNAMIC_SCREEN_MIN_UI_VERSION,
    MAX_CHART_SERIES,
    MAX_CHART_LABEL_BYTES,
    MAX_SCREEN_NODES,
    MAX_SCREEN_OPTIONS,
    NATIVE_SLOTS,
    NATIVE_SLOT_CONTEXT_KEYS,
    PRIMITIVES,
    PRIMITIVE_SPECS,
    PLUGIN_CONTEXT_REQUESTS,
    capUtf8Bytes,
    boundRpcDisplay,
    pluginCompatibilityError,
    pluginIsCompatible,
    sanitizeDisplayText,
    parseManifest,
    parsePluginManifest,
    parsePluginAction,
    parsePluginScreenParams,
    tryParseManifest,
} from './plugins/index.js';

export type {
    RealtimeClientFrame,
    RealtimeControlAction,
    RealtimeHostFrame,
    RealtimePluginOpenFrame,
    RealtimePluginPublicContext,
    RealtimePluginPublicSession,
    RealtimeState,
} from './realtime/index.js';
export {
    encodeRealtimeFrame,
    MAX_REALTIME_AUDIO_BASE64_BYTES,
    MAX_REALTIME_TEXT_BYTES,
    MAX_REALTIME_PUBLIC_SESSIONS,
    MAX_REALTIME_SDP_BYTES,
    MAX_REALTIME_WEBRTC_DATA_BYTES,
    newRealtimeChannel,
    parseRealtimeClientFrame,
    parseRealtimeHostFrame,
    boundRealtimePublicContext,
    realtimePluginPublicContext,
    REALTIME_INPUT_RATE,
    REALTIME_OUTPUT_RATE,
    realtimePcm16ByteLength,
    realtimeSocketUrl,
} from './realtime/index.js';
