export type {
    DeviceKind,
    PeerAuthorityMetadata,
    PeerCapability,
    PeerDescriptorClaims,
    PeerGrantConstraintError,
    PeerMutationMetadata,
    PeerMutationRejection,
    PeerRelationship,
    PeerRelationshipState,
    SignedPeerDescriptor,
} from './domain/peer.js';
export {
    DEFAULT_PEER_CAPABILITIES,
    inspectPeerGrantConstraints,
    inspectPeerMutation,
    isPeerCapabilities,
    PEER_CAPABILITIES,
    PEER_MUTATION_CLOCK_SKEW_MS,
    PEER_MUTATION_MAX_TTL_MS,
    PEER_MUTATION_TTL_MS,
    parseDeviceKind,
    deviceIsPeer,
    parsePeerAllowlist,
    peerCapabilityForRequest,
    peerMayDispatch,
} from './domain/peer.js';
